#!/usr/bin/env ruby
#require File.dirname(__FILE__) + '/../config/boot'
#require 'commands/server'

require './lib/tick_stats'
require 'commands/server'

# run TickStats::Server
# $:.unshift File.join(File.expand_path(File.dirname(__FILE__)), 'config')
